version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: todolist

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - main
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile

    depends_on:
      - db
    networks:
      - main
    ports:
      - 3000:5000
networks:
  main:
    driver: bridge